Supported mysqli & improved enable extensions logic (#6)
Co-authored-by: Elon Niu <elonniu@amazon.com>

diff --git a/src/php-74-fpm-nginx/runtime/bootstrap b/src/php-74-fpm-nginx/runtime/bootstrap
--- a/src/php-74-fpm-nginx/runtime/bootstrap
+++ b/src/php-74-fpm-nginx/runtime/bootstrap
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+
+# Fail on error
+set -e
 
 if [ ! -d '/tmp/session' ]; then
   mkdir -p /tmp/session
@@ -9,6 +12,17 @@ if [ -f "/var/task/bootstrap" ]; then
   exec -- /var/task/bootstrap
 else
   echo "Running '/opt/bootstrap' when '/var/task/bootstrap' not found"
-  /opt/php/bin/php-fpm --force-stderr
-  exec /opt/nginx/bin/nginx -g "daemon off;"
+
+  if [ -f "/var/task/php/etc/php-fpm.conf" ]; then
+    /opt/php/bin/php-fpm --force-stderr --fpm-config /var/task/php/etc/php-fpm.conf
+  else
+    /opt/php/bin/php-fpm --force-stderr --fpm-config /opt/php/etc/php-fpm.conf
+  fi
+
+  if [ -f "/var/task/nginx/conf/nginx.conf" ]; then
+    exec /opt/nginx/bin/nginx -c /var/task/nginx/conf/nginx.conf -g "daemon off;"
+  else
+    exec /opt/nginx/bin/nginx -c /opt/nginx/conf/nginx.conf -g "daemon off;"
+  fi
+
 fi
