Supported mysqli & improved enable extensions logic

diff --git a/src/nginx-123/runtime/bootstrap b/src/nginx-123/runtime/bootstrap
--- a/src/nginx-123/runtime/bootstrap
+++ b/src/nginx-123/runtime/bootstrap
@@ -1,9 +1,18 @@
-#!/bin/bash
+#!/bin/sh
+
+# Fail on error
+set -e
 
 if [ -f "/var/task/bootstrap" ]; then
   echo "Found and Running '/var/task/bootstrap' instead of '/opt/bootstrap'"
   exec -- /var/task/bootstrap
 else
   echo "Running '/opt/bootstrap' when '/var/task/bootstrap' not found"
-  exec /opt/nginx/bin/nginx -g "daemon off;"
+
+  if [ -f "/var/task/nginx/conf/nginx.conf" ]; then
+    exec /opt/nginx/bin/nginx -c /var/task/nginx/conf/nginx.conf -g "daemon off;"
+  else
+    exec /opt/nginx/bin/nginx -c /opt/nginx/conf/nginx.conf -g "daemon off;"
+  fi
+
 fi
